### PR TITLE
@@calculation_method -> @calculation_method

### PR DESCRIPTION
**Pull request by flvrone**

### CODE REVIEW

**Comment by karatedog** [comment]
Thanks. In the meantime I have heavily modified the file, and this has already been fixed. I want to push a new version soon although I have limited time with this gem.

**Comment by flvrone** [comment]
Nice, will wait for your update :)

**Comment by qume** [comment]
Any chance this PR could be accepted, so that the rubygems version of this works?

**Comment by karatedog** [comment]
Sorry guys, got distracted with tons of personal matters.

**Pull request merged**
